# Generated by Django 2.1.1 on 2019-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afectiuni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificare', models.CharField(blank=True, max_length=200, null=True)),
                ('DecontatCNAS', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AfectiuniStatiuni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afectiune', models.ForeignKey(on_delete='cascade', related_name='afectiune', to='afectiuni.Afectiuni')),
            ],
        ),
        migrations.CreateModel(
            name='BazaTratament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedura', models.CharField(blank=True, max_length=100, null=True)),
                ('cosnsultatieMedicala', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cazare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatiuniBalneare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(blank=True, max_length=100, null=True)),
                ('judet', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cazare',
            name='statiune',
            field=models.ForeignKey(on_delete='cascade', to='afectiuni.StatiuniBalneare'),
        ),
        migrations.AddField(
            model_name='bazatratament',
            name='statiune',
            field=models.ForeignKey(on_delete='cascade', to='afectiuni.StatiuniBalneare'),
        ),
        migrations.AddField(
            model_name='afectiunistatiuni',
            name='statiune',
            field=models.ForeignKey(on_delete='cascade', related_name='statiune', to='afectiuni.StatiuniBalneare'),
        ),
        migrations.AddField(
            model_name='afectiuni',
            name='StatiuneTratament',
            field=models.ManyToManyField(through='afectiuni.AfectiuniStatiuni', to='afectiuni.StatiuniBalneare'),
        ),
    ]
