# Generated by Django 2.1.1 on 2019-05-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afectiuni', '0002_auto_20190512_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceduri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
